/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const GraphEdge: CompiledShader<{ aQuad: 'vec2' }, { iStart: 'vec2'; iEnd: 'vec2'; iColor: 'vec4' }, { uScale: 'float'; uOffset: 'vec2'; uViewport: 'vec2'; uWidth: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uScale : f32,
  uOffset : vec2f,
  uViewport : vec2f,
  uWidth : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aQuad : vec2f,
  @location(1) iStart : vec2f,
  @location(2) iEnd : vec2f,
  @location(3) iColor : vec4f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vColor : vec4f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vColor = bm_in.iColor;
  let a = (bm_in.iStart - bm_u.uOffset) * bm_u.uScale + bm_u.uViewport * 0.5;
  let b = (bm_in.iEnd - bm_u.uOffset) * bm_u.uScale + bm_u.uViewport * 0.5;
  let along = b - a;
  let dir = normalize(along);
  let n = vec2f(0.0 - dir.y, dir.x);
  let p = a + along * bm_in.aQuad.y + n * (bm_in.aQuad.x * bm_u.uWidth * 0.5);
  let clipX = p.x / bm_u.uViewport.x * 2.0 - 1.0;
  let clipY = 1.0 - p.y / bm_u.uViewport.y * 2.0;
  bm_out.bm_position = vec4f(vec2f(clipX, clipY), 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  return vec4f(bm_in.vColor.xyz * bm_in.vColor.w, bm_in.vColor.w);
}
`,
  attributes: { aQuad: 'vec2' },
  instanceAttributes: { iStart: 'vec2', iEnd: 'vec2', iColor: 'vec4' },
  uniforms: { uScale: 'float', uOffset: 'vec2', uViewport: 'vec2', uWidth: 'float' },
  layout: {"attributes":[{"name":"aQuad","type":"vec2","location":0,"size":2,"divisor":0},{"name":"iStart","type":"vec2","location":1,"size":2,"divisor":1},{"name":"iEnd","type":"vec2","location":2,"size":2,"divisor":1},{"name":"iColor","type":"vec4","location":3,"size":4,"divisor":1}],"uniforms":[{"name":"uScale","type":"float","kind":"1f","size":1,"offset":0},{"name":"uOffset","type":"vec2","kind":"2fv","size":2,"offset":8},{"name":"uViewport","type":"vec2","kind":"2fv","size":2,"offset":16},{"name":"uWidth","type":"float","kind":"1f","size":1,"offset":24}],"uniformBlockSize":32},

};

export default GraphEdge;
