/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const GraphNode: CompiledShader<{ aCorner: 'vec2' }, { iCenter: 'vec2'; iRadius: 'float'; iTint: 'vec3'; iFlags: 'float' }, { uScale: 'float'; uOffset: 'vec2'; uViewport: 'vec2' }> = {
  wgslSrc: `struct BmUniforms {
  uScale : f32,
  uOffset : vec2f,
  uViewport : vec2f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aCorner : vec2f,
  @location(1) iCenter : vec2f,
  @location(2) iRadius : f32,
  @location(3) iTint : vec3f,
  @location(4) iFlags : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
  @location(1) vTint : vec3f,
  @location(2) vFlags : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aCorner;
  bm_out.vTint = bm_in.iTint;
  bm_out.vFlags = bm_in.iFlags;
  let world = bm_in.iCenter + bm_in.aCorner * (bm_in.iRadius * 1.25);
  let screen = (world - bm_u.uOffset) * bm_u.uScale + bm_u.uViewport * 0.5;
  let clipX = screen.x / bm_u.uViewport.x * 2.0 - 1.0;
  let clipY = 1.0 - screen.y / bm_u.uViewport.y * 2.0;
  bm_out.bm_position = vec4f(vec2f(clipX, clipY), 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let s = bm_in.vUv * 1.25;
  let d = length(s);
  let fill = 1.0 - smoothstep(0.9, 1.0, d);
  let ring = smoothstep(1.04, 1.1, d) * (1.0 - smoothstep(1.16, 1.24, d));
  let color = bm_in.vTint * (1.0 + bm_in.vFlags * 0.25) + vec3f(1.0, 1.0, 1.0) * (ring * bm_in.vFlags * 0.9);
  let alpha = max(fill, ring * bm_in.vFlags);
  return vec4f(color * alpha, alpha);
}
`,
  attributes: { aCorner: 'vec2' },
  instanceAttributes: { iCenter: 'vec2', iRadius: 'float', iTint: 'vec3', iFlags: 'float' },
  uniforms: { uScale: 'float', uOffset: 'vec2', uViewport: 'vec2' },
  layout: {"attributes":[{"name":"aCorner","type":"vec2","location":0,"size":2,"divisor":0},{"name":"iCenter","type":"vec2","location":1,"size":2,"divisor":1},{"name":"iRadius","type":"float","location":2,"size":1,"divisor":1},{"name":"iTint","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iFlags","type":"float","location":4,"size":1,"divisor":1}],"uniforms":[{"name":"uScale","type":"float","kind":"1f","size":1,"offset":0},{"name":"uOffset","type":"vec2","kind":"2fv","size":2,"offset":8},{"name":"uViewport","type":"vec2","kind":"2fv","size":2,"offset":16}],"uniformBlockSize":32},

};

export default GraphNode;
