/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const HeroLogo: CompiledShader<{ aCorner: 'vec2' }, Record<string, never>, { uViewProj: 'mat4'; uTex: 'sampler2D'; uMouse: 'vec2' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uMouse : vec2f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
struct BmVSIn {
  @location(0) aCorner : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aCorner * 0.5 + vec2f(0.5, 0.5);
  let yaw = bm_u.uMouse.x * 0.4;
  let cy = cos(yaw);
  let sy = sin(yaw);
  let tilt = bm_u.uMouse.y * 0.22;
  let ct = cos(tilt);
  let st = sin(tilt);
  let cx = 2.55 + bm_in.aCorner.x * 0.26;
  let px = cx * cy + 0.3 * sy;
  let pz0 = 0.3 * cy - cx * sy;
  let py = bm_in.aCorner.y * 0.26 * ct - pz0 * st;
  let pz1 = bm_in.aCorner.y * 0.26 * st + pz0 * ct;
  bm_out.bm_position = bm_u.uViewProj * vec4f(vec3f(px, py, pz1), 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let d = length(bm_in.vUv - vec2f(0.5, 0.5)) * 2.0;
  let mask = 1.0 - smoothstep(0.86, 0.96, d);
  let c = textureSample(uTex, uTex_sampler, bm_in.vUv);
  return vec4f(c.x, c.y, c.z, c.w * mask * 0.96);
}
`,
  attributes: { aCorner: 'vec2' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uTex: 'sampler2D', uMouse: 'vec2' },
  layout: {"attributes":[{"name":"aCorner","type":"vec2","location":0,"size":2,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uMouse","type":"vec2","kind":"2fv","size":2,"offset":64}],"uniformBlockSize":80},

};

export default HeroLogo;
