/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const HeroDag: CompiledShader<{ aCorner: 'vec2' }, { iPos: 'vec3'; iKind: 'float'; iSeed: 'float' }, { uViewProj: 'mat4'; uTime: 'float'; uMouse: 'vec2'; uScroll: 'float'; uWrap: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uTime : f32,
  uMouse : vec2f,
  uScroll : f32,
  uWrap : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aCorner : vec2f,
  @location(1) iPos : vec3f,
  @location(2) iKind : f32,
  @location(3) iSeed : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
  @location(1) vColor : vec3f,
  @location(2) vAlpha : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aCorner;
  var color = vec3f(1.0, 0.66, 0.3);
  var size = 0.034 + fract(bm_in.iSeed * 7.3) * 0.014;
  var glow = 0.85 + fract(bm_in.iSeed * 4.7) * 0.55;
  if (bm_in.iKind > 0.5 && bm_in.iKind < 1.5) {
    color = vec3f(0.35, 0.68, 1.0);
  } else {
    if (bm_in.iKind > 1.5) {
      color = vec3f(0.95, 0.97, 1.0);
      size = 0.034 + fract(bm_in.iSeed * 5.1) * 0.008;
      glow = 1.1;
    }
  }
  let wrap = max(bm_u.uWrap, 0.001);
  let x = ((bm_in.iPos.x + bm_u.uScroll) - (wrap) * floor((bm_in.iPos.x + bm_u.uScroll) / (wrap))) - wrap + 3.0;
  let born = x + wrap - 3.0;
  let grown = smoothstep(0.0, 4.2, born);
  var p = vec3f(x + bm_u.uMouse.x * 0.08, bm_in.iPos.y + sin(bm_u.uTime * 0.6 + bm_in.iSeed * 6.2832) * 0.02 - bm_u.uMouse.y * 0.05, 0.0);
  let world = p + vec3f(bm_in.aCorner.x * size * grown, bm_in.aCorner.y * size * grown, 0.0);
  bm_out.vColor = color;
  bm_out.vAlpha = glow * grown;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let d = length(bm_in.vUv);
  let core = 1.0 - smoothstep(0.5, 1.0, d);
  return vec4f(bm_in.vColor, core * bm_in.vAlpha);
}
`,
  attributes: { aCorner: 'vec2' },
  instanceAttributes: { iPos: 'vec3', iKind: 'float', iSeed: 'float' },
  uniforms: { uViewProj: 'mat4', uTime: 'float', uMouse: 'vec2', uScroll: 'float', uWrap: 'float' },
  layout: {"attributes":[{"name":"aCorner","type":"vec2","location":0,"size":2,"divisor":0},{"name":"iPos","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iKind","type":"float","location":2,"size":1,"divisor":1},{"name":"iSeed","type":"float","location":3,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":64},{"name":"uMouse","type":"vec2","kind":"2fv","size":2,"offset":72},{"name":"uScroll","type":"float","kind":"1f","size":1,"offset":80},{"name":"uWrap","type":"float","kind":"1f","size":1,"offset":84}],"uniformBlockSize":96},

};

export default HeroDag;
