/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const HeroVeil: CompiledShader<{ aCorner: 'vec2' }, { iPos: 'vec3'; iKind: 'float'; iSeed: 'float' }, { uViewProj: 'mat4'; uTime: 'float'; uMouse: 'vec2' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uTime : f32,
  uMouse : vec2f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aCorner : vec2f,
  @location(1) iPos : vec3f,
  @location(2) iKind : f32,
  @location(3) iSeed : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
  @location(1) vColor : vec3f,
  @location(2) vAlpha : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aCorner;
  var p = bm_in.iPos;
  var size = 0.02;
  var color = vec3f(0.55, 0.65, 0.85);
  var glow = 0.5;
  if (bm_in.iKind < 0.5) {
    size = 0.013 + bm_in.iSeed * 0.007;
    color = mix(vec3f(0.38, 0.48, 0.68), vec3f(0.62, 0.74, 1.0), fract(bm_in.iSeed * 9.1));
    glow = 0.3 + fract(bm_in.iSeed * 3.7) * 0.3;
  } else {
    if (bm_in.iKind < 1.5) {
      let a = bm_in.iSeed * 6.2832 + bm_u.uTime * 0.42;
      let r = 1.55 + 0.3 * sin(bm_in.iSeed * 39.7);
      let y = 1.5 - ((bm_in.iSeed * 3.7 + bm_u.uTime * 0.055) - (1.0) * floor((bm_in.iSeed * 3.7 + bm_u.uTime * 0.055) / (1.0))) * 3.0;
      p = vec3f(cos(a) * r, y, sin(a) * r);
      size = 0.013 + fract(bm_in.iSeed * 7.3) * 0.01;
      color = mix(vec3f(1.0, 0.58, 0.22), vec3f(1.0, 0.82, 0.45), fract(bm_in.iSeed * 5.9));
      glow = 0.65 + fract(bm_in.iSeed * 4.7) * 0.55;
    } else {
      let a = -(bm_in.iSeed * 6.2832 + bm_u.uTime * 0.58);
      let r = 1.55 + 0.3 * cos(bm_in.iSeed * 41.3);
      let y = -1.5 + ((bm_in.iSeed * 2.9 + bm_u.uTime * 0.075) - (1.0) * floor((bm_in.iSeed * 2.9 + bm_u.uTime * 0.075) / (1.0))) * 3.0;
      p = vec3f(cos(a) * r, y, sin(a) * r);
      size = 0.012 + fract(bm_in.iSeed * 6.1) * 0.009;
      color = mix(vec3f(0.3, 0.65, 1.0), vec3f(0.55, 0.85, 1.0), fract(bm_in.iSeed * 8.3));
      glow = 0.7 + fract(bm_in.iSeed * 4.3) * 0.5;
    }
  }
  let yaw = bm_u.uTime * 0.07 + bm_u.uMouse.x * 0.4;
  let cy = cos(yaw);
  let sy = sin(yaw);
  let px = p.x * cy + p.z * sy;
  let pz0 = p.z * cy - p.x * sy;
  let tilt = bm_u.uMouse.y * 0.22;
  let ct = cos(tilt);
  let st = sin(tilt);
  let py = p.y * ct - pz0 * st;
  let pz1 = p.y * st + pz0 * ct;
  p = vec3f(px, py, pz1);
  let depthFade = clamp((p.z + 3.4) / 4.8, 0.12, 1.0);
  let isStream = step(0.5, bm_in.iKind);
  let centerCalm = mix(1.0, 0.55 + 0.45 * clamp(abs(p.y), 0.0, 1.0), isStream);
  let world = p + vec3f(bm_in.aCorner.x * size, bm_in.aCorner.y * size, 0.0);
  bm_out.vColor = color;
  bm_out.vAlpha = depthFade * glow * centerCalm;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let d = length(bm_in.vUv);
  let core = 1.0 - smoothstep(0.5, 1.0, d);
  return vec4f(bm_in.vColor, core * bm_in.vAlpha);
}
`,
  attributes: { aCorner: 'vec2' },
  instanceAttributes: { iPos: 'vec3', iKind: 'float', iSeed: 'float' },
  uniforms: { uViewProj: 'mat4', uTime: 'float', uMouse: 'vec2' },
  layout: {"attributes":[{"name":"aCorner","type":"vec2","location":0,"size":2,"divisor":0},{"name":"iPos","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iKind","type":"float","location":2,"size":1,"divisor":1},{"name":"iSeed","type":"float","location":3,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":64},{"name":"uMouse","type":"vec2","kind":"2fv","size":2,"offset":72}],"uniformBlockSize":80},

};

export default HeroVeil;
