/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const HeroEdges: CompiledShader<{ aQuad: 'vec2' }, { iStart: 'vec3'; iEnd: 'vec3'; iTint: 'vec3' }, { uViewProj: 'mat4'; uMouse: 'vec2'; uWidth: 'float'; uScroll: 'float'; uWrap: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uMouse : vec2f,
  uWidth : f32,
  uScroll : f32,
  uWrap : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aQuad : vec2f,
  @location(1) iStart : vec3f,
  @location(2) iEnd : vec3f,
  @location(3) iTint : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vTint : vec3f,
  @location(1) vAlong : f32,
  @location(2) vFade : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vTint = bm_in.iTint;
  bm_out.vAlong = bm_in.aQuad.y;
  let AHEAD = 3.0;
  let sx = ((bm_in.iStart.x + bm_u.uScroll) - (bm_u.uWrap) * floor((bm_in.iStart.x + bm_u.uScroll) / (bm_u.uWrap))) - bm_u.uWrap + AHEAD;
  let ex = ((bm_in.iEnd.x + bm_u.uScroll) - (bm_u.uWrap) * floor((bm_in.iEnd.x + bm_u.uScroll) / (bm_u.uWrap))) - bm_u.uWrap + AHEAD;
  bm_out.vFade = 1.0 - smoothstep(1.2, 1.8, abs(sx - ex));
  let a2 = vec3f(sx + bm_u.uMouse.x * 0.08, bm_in.iStart.y - bm_u.uMouse.y * 0.05, 0.0);
  let b2 = vec3f(ex + bm_u.uMouse.x * 0.08, bm_in.iEnd.y - bm_u.uMouse.y * 0.05, 0.0);
  let dir = b2 - a2;
  let len = length(dir);
  let n = dir * (1.0 / max(len, 0.0001));
  let perp = vec3f(-n.y, n.x, 0.0);
  let p = a2 + n * (bm_in.aQuad.y * len) + perp * (bm_in.aQuad.x * bm_u.uWidth * 0.5);
  bm_out.bm_position = bm_u.uViewProj * vec4f(p, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let taper = smoothstep(0.0, 0.08, bm_in.vAlong) * (1.0 - smoothstep(0.92, 1.0, bm_in.vAlong));
  return vec4f(bm_in.vTint, taper * 0.85 * bm_in.vFade);
}
`,
  attributes: { aQuad: 'vec2' },
  instanceAttributes: { iStart: 'vec3', iEnd: 'vec3', iTint: 'vec3' },
  uniforms: { uViewProj: 'mat4', uMouse: 'vec2', uWidth: 'float', uScroll: 'float', uWrap: 'float' },
  layout: {"attributes":[{"name":"aQuad","type":"vec2","location":0,"size":2,"divisor":0},{"name":"iStart","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iEnd","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iTint","type":"vec3","location":3,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uMouse","type":"vec2","kind":"2fv","size":2,"offset":64},{"name":"uWidth","type":"float","kind":"1f","size":1,"offset":72},{"name":"uScroll","type":"float","kind":"1f","size":1,"offset":76},{"name":"uWrap","type":"float","kind":"1f","size":1,"offset":80}],"uniformBlockSize":96},

};

export default HeroEdges;
