/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const HeroDag: CompiledShader<{ aCorner: 'vec2' }, { iIdx: 'float'; iKind: 'float'; iSeed: 'float' }, { uViewProj: 'mat4'; uTime: 'float'; uMouse: 'vec2'; uNow: 'float'; uNodes: 'storage' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uTime : f32,
  uMouse : vec2f,
  uNow : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var<storage, read> uNodes : array<vec4f>;
struct BmVSIn {
  @location(0) aCorner : vec2f,
  @location(1) iIdx : f32,
  @location(2) iKind : f32,
  @location(3) iSeed : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
  @location(1) vColor : vec3f,
  @location(2) vAlpha : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aCorner;
  let node = uNodes[u32(bm_in.iIdx)];
  let grown = smoothstep(node.w, node.w + 2.8, bm_u.uNow);
  var color = vec3f(0.92, 0.42, 0.55);
  var sizeMul = 1.0;
  if (bm_in.iKind > 0.5 && bm_in.iKind < 1.5) {
    color = vec3f(0.35, 0.85, 0.6);
  } else {
    if (bm_in.iKind > 1.5 && bm_in.iKind < 2.5) {
      color = vec3f(0.95, 0.75, 0.8);
    } else {
      if (bm_in.iKind > 2.5 && bm_in.iKind < 3.5) {
        color = vec3f(0.95, 0.72, 0.35);
        sizeMul = 1.35;
      } else {
        if (bm_in.iKind > 3.5 && bm_in.iKind < 4.5) {
          color = vec3f(0.65, 0.5, 0.95);
          sizeMul = 0.95;
        } else {
          if (bm_in.iKind > 4.5 && bm_in.iKind < 5.5) {
            color = vec3f(0.45, 0.7, 1.0);
            sizeMul = 0.9;
          } else {
            if (bm_in.iKind > 5.5 && bm_in.iKind < 6.5) {
              color = vec3f(0.8, 0.42, 0.75);
              sizeMul = 0.9;
            } else {
              if (bm_in.iKind > 6.5 && bm_in.iKind < 7.5) {
                color = vec3f(0.95, 0.85, 0.4);
                sizeMul = 1.15;
              } else {
                if (bm_in.iKind > 7.5 && bm_in.iKind < 8.5) {
                  color = vec3f(0.95, 0.6, 0.35);
                  sizeMul = 1.1;
                } else {
                  if (bm_in.iKind > 8.5 && bm_in.iKind < 9.5) {
                    color = vec3f(0.75, 0.8, 0.95);
                    sizeMul = 1.2;
                  } else {
                    if (bm_in.iKind > 9.5) {
                      color = vec3f(0.42, 0.44, 0.52);
                      sizeMul = 0.55;
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  var size = (0.03 + fract(bm_in.iSeed * 7.3) * 0.012) * sizeMul * (0.25 + 0.75 * grown);
  var glowBase = 0.8 + fract(bm_in.iSeed * 4.7) * 0.5;
  if (bm_in.iKind > 9.5) {
    glowBase = 0.4;
  }
  var glow = glowBase * grown;
  let bobY = sin(bm_u.uTime * 1.5 + node.w * 13.7) * 0.022 * grown;
  let bobX = cos(bm_u.uTime * 1.1 + node.w * 27.3) * 0.012 * grown;
  var p = vec3f(node.x + bobX, node.y + bobY, node.z);
  let yaw = bm_u.uTime * 0.22 + bm_u.uMouse.x * 0.5;
  let cy = cos(yaw);
  let sy = sin(yaw);
  let px = p.x * cy + p.z * sy;
  let pz0 = p.z * cy - p.x * sy;
  let tilt = 0.42 + bm_u.uMouse.y * 0.18;
  let ct = cos(tilt);
  let st = sin(tilt);
  let py = p.y * ct - pz0 * st;
  let pz1 = p.y * st + pz0 * ct;
  p = vec3f(px, py, pz1);
  let depthFade = clamp((p.z + 3.4) / 4.6, 0.25, 1.0);
  let world = p + vec3f(bm_in.aCorner.x * size, bm_in.aCorner.y * size, 0.0);
  bm_out.vColor = color;
  bm_out.vAlpha = depthFade * glow;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let d = length(bm_in.vUv);
  let core = 1.0 - smoothstep(0.0, 0.32, d);
  let halo = (1.0 - smoothstep(0.1, 1.0, d)) * 0.5;
  return vec4f(bm_in.vColor, (core + halo) * bm_in.vAlpha);
}
`,
  attributes: { aCorner: 'vec2' },
  instanceAttributes: { iIdx: 'float', iKind: 'float', iSeed: 'float' },
  uniforms: { uViewProj: 'mat4', uTime: 'float', uMouse: 'vec2', uNow: 'float', uNodes: 'storage' },
  layout: {"attributes":[{"name":"aCorner","type":"vec2","location":0,"size":2,"divisor":0},{"name":"iIdx","type":"float","location":1,"size":1,"divisor":1},{"name":"iKind","type":"float","location":2,"size":1,"divisor":1},{"name":"iSeed","type":"float","location":3,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":64},{"name":"uMouse","type":"vec2","kind":"2fv","size":2,"offset":72},{"name":"uNow","type":"float","kind":"1f","size":1,"offset":80},{"name":"uNodes","type":"storage","kind":"1i","size":1,"unit":0,"textureBinding":1}],"uniformBlockSize":96},

};

export default HeroDag;
