/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const HeroEdges: CompiledShader<{ aQuad: 'vec2' }, { iStart: 'vec3'; iEnd: 'vec3'; iTint: 'vec3'; iBirth: 'float' }, { uViewProj: 'mat4'; uTime: 'float'; uMouse: 'vec2'; uWidth: 'float'; uNow: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uTime : f32,
  uMouse : vec2f,
  uWidth : f32,
  uNow : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aQuad : vec2f,
  @location(1) iStart : vec3f,
  @location(2) iEnd : vec3f,
  @location(3) iTint : vec3f,
  @location(4) iBirth : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vTint : vec3f,
  @location(1) vAlong : f32,
  @location(2) vBirth : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vTint = bm_in.iTint;
  bm_out.vAlong = bm_in.aQuad.y;
  bm_out.vBirth = bm_in.iBirth;
  let yaw = bm_u.uTime * 0.22 + bm_u.uMouse.x * 0.5;
  let tilt = 0.42 + bm_u.uMouse.y * 0.18;
  let cy = cos(yaw);
  let sy = sin(yaw);
  let ct = cos(tilt);
  let st = sin(tilt);
  let ax = bm_in.iStart.x * cy + bm_in.iStart.z * sy;
  let az0 = bm_in.iStart.z * cy - bm_in.iStart.x * sy;
  let ay = bm_in.iStart.y * ct - az0 * st;
  let az1 = bm_in.iStart.y * st + az0 * ct;
  let a2 = vec3f(ax, ay, az1);
  let bx = bm_in.iEnd.x * cy + bm_in.iEnd.z * sy;
  let bz0 = bm_in.iEnd.z * cy - bm_in.iEnd.x * sy;
  let by = bm_in.iEnd.y * ct - bz0 * st;
  let bz1 = bm_in.iEnd.y * st + bz0 * ct;
  let b2 = vec3f(bx, by, bz1);
  let dir = b2 - a2;
  let len = length(dir);
  let n = dir * (1.0 / max(len, 0.0001));
  let perp = vec3f(-n.y, n.x, 0.0);
  let p = a2 + n * (bm_in.aQuad.y * len) + perp * (bm_in.aQuad.x * bm_u.uWidth * 0.5);
  bm_out.bm_position = bm_u.uViewProj * vec4f(p, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let taper = smoothstep(0.0, 0.08, bm_in.vAlong) * (1.0 - smoothstep(0.92, 1.0, bm_in.vAlong));
  let grown = smoothstep(bm_in.vBirth, bm_in.vBirth + 1.6, bm_u.uNow) * (1.0 - smoothstep(23.2, 25.9, bm_u.uNow));
  return vec4f(bm_in.vTint, taper * 0.8 * grown);
}
`,
  attributes: { aQuad: 'vec2' },
  instanceAttributes: { iStart: 'vec3', iEnd: 'vec3', iTint: 'vec3', iBirth: 'float' },
  uniforms: { uViewProj: 'mat4', uTime: 'float', uMouse: 'vec2', uWidth: 'float', uNow: 'float' },
  layout: {"attributes":[{"name":"aQuad","type":"vec2","location":0,"size":2,"divisor":0},{"name":"iStart","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iEnd","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iTint","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iBirth","type":"float","location":4,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":64},{"name":"uMouse","type":"vec2","kind":"2fv","size":2,"offset":72},{"name":"uWidth","type":"float","kind":"1f","size":1,"offset":80},{"name":"uNow","type":"float","kind":"1f","size":1,"offset":84}],"uniformBlockSize":96},

};

export default HeroEdges;
