/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const HeroEdges: CompiledShader<{ aQuad: 'vec2' }, { iA: 'float'; iB: 'float'; iTint: 'vec3'; iBirth: 'float' }, { uViewProj: 'mat4'; uTime: 'float'; uMouse: 'vec2'; uWidth: 'float'; uNow: 'float'; uNodes: 'storage' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uTime : f32,
  uMouse : vec2f,
  uWidth : f32,
  uNow : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var<storage, read> uNodes : array<vec4f>;
struct BmVSIn {
  @location(0) aQuad : vec2f,
  @location(1) iA : f32,
  @location(2) iB : f32,
  @location(3) iTint : vec3f,
  @location(4) iBirth : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vTint : vec3f,
  @location(1) vAlong : f32,
  @location(2) vBirth : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vTint = bm_in.iTint;
  bm_out.vAlong = bm_in.aQuad.y;
  bm_out.vBirth = bm_in.iBirth;
  let na = uNodes[u32(bm_in.iA)];
  let nb = uNodes[u32(bm_in.iB)];
  let gA = smoothstep(na.w, na.w + 2.8, bm_u.uNow);
  let gB = smoothstep(nb.w, nb.w + 2.8, bm_u.uNow);
  let start = vec3f(na.x + cos(bm_u.uTime * 1.1 + na.w * 27.3) * 0.012 * gA, na.y + sin(bm_u.uTime * 1.5 + na.w * 13.7) * 0.022 * gA, na.z);
  let end = vec3f(nb.x + cos(bm_u.uTime * 1.1 + nb.w * 27.3) * 0.012 * gB, nb.y + sin(bm_u.uTime * 1.5 + nb.w * 13.7) * 0.022 * gB, nb.z);
  let yaw = bm_u.uTime * 0.22 + bm_u.uMouse.x * 0.5;
  let tilt = 0.42 + bm_u.uMouse.y * 0.18;
  let cy = cos(yaw);
  let sy = sin(yaw);
  let ct = cos(tilt);
  let st = sin(tilt);
  let ax = start.x * cy + start.z * sy;
  let az0 = start.z * cy - start.x * sy;
  let ay = start.y * ct - az0 * st;
  let az1 = start.y * st + az0 * ct;
  let a2 = vec3f(ax, ay, az1);
  let bx = end.x * cy + end.z * sy;
  let bz0 = end.z * cy - end.x * sy;
  let by = end.y * ct - bz0 * st;
  let bz1 = end.y * st + bz0 * ct;
  let b2 = vec3f(bx, by, bz1);
  let dir = b2 - a2;
  let len = length(dir);
  let n = dir * (1.0 / max(len, 0.0001));
  let perp = vec3f(-n.y, n.x, 0.0);
  let p = a2 + n * (bm_in.aQuad.y * len) + perp * (bm_in.aQuad.x * bm_u.uWidth * 0.5);
  bm_out.bm_position = bm_u.uViewProj * vec4f(p, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let taper = smoothstep(0.0, 0.08, bm_in.vAlong) * (1.0 - smoothstep(0.92, 1.0, bm_in.vAlong));
  let reach = smoothstep(bm_in.vBirth + 0.3, bm_in.vBirth + 1.9, bm_u.uNow) * 1.15;
  let behindTip = 1.0 - smoothstep(reach - 0.14, reach, bm_in.vAlong);
  let grown = smoothstep(bm_in.vBirth, bm_in.vBirth + 0.5, bm_u.uNow);
  return vec4f(bm_in.vTint, taper * 0.8 * behindTip * grown);
}
`,
  attributes: { aQuad: 'vec2' },
  instanceAttributes: { iA: 'float', iB: 'float', iTint: 'vec3', iBirth: 'float' },
  uniforms: { uViewProj: 'mat4', uTime: 'float', uMouse: 'vec2', uWidth: 'float', uNow: 'float', uNodes: 'storage' },
  layout: {"attributes":[{"name":"aQuad","type":"vec2","location":0,"size":2,"divisor":0},{"name":"iA","type":"float","location":1,"size":1,"divisor":1},{"name":"iB","type":"float","location":2,"size":1,"divisor":1},{"name":"iTint","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iBirth","type":"float","location":4,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":64},{"name":"uMouse","type":"vec2","kind":"2fv","size":2,"offset":72},{"name":"uWidth","type":"float","kind":"1f","size":1,"offset":80},{"name":"uNow","type":"float","kind":"1f","size":1,"offset":84},{"name":"uNodes","type":"storage","kind":"1i","size":1,"unit":0,"textureBinding":1}],"uniformBlockSize":96},

};

export default HeroEdges;
