import { deepStrictEqual, equal, notEqual, ok, throws } from "node:assert/strict";
import { readFileSync } from "node:fs";
import { coreCall, initCore } from "../src/lib/engine/core";
import { decodeChange, encodeChange, changeId } from "../src/lib/engine/proto";
import { packCoreValueMaps, unpackCoreValueMaps } from "../src/lib/engine/core-values";
import type { ChangeJSON } from "../src/lib/engine/contracts";

interface CodecFixture {
	name: string;
	preimageHex: string;
	bytesHex: string;
	id: string;
	malformedBytesHex?: string;
}

// Native codec_test.odin embeds this same fixed corpus. No expected result is
// generated by either runtime under test, and no live relay/data is required.
const fixtures: CodecFixture[] = JSON.parse(readFileSync(
	new URL("../../glonOdin/core/codec_fixtures.json", import.meta.url), "utf8",
));
await initCore({ wasmBytes: readFileSync(new URL("../static/engine.wasm", import.meta.url)) });
for (const fixture of fixtures) {
	if (fixture.malformedBytesHex) {
		equal(decodeChange(Uint8Array.from(Buffer.from(fixture.malformedBytesHex, "hex"))), null, `${fixture.name}: original malformed golden`);
	}
	const bytes = Uint8Array.from(Buffer.from(fixture.bytesHex, "hex"));
	const decoded = decodeChange(bytes);
	ok(decoded, `${fixture.name}: decode`);
	equal(decoded.id, fixture.id, `${fixture.name}: embedded id`);
	equal(changeId(decoded), fixture.id, `${fixture.name}: canonical hash`);
	equal(Buffer.from(encodeChange(decoded)).toString("hex"), fixture.bytesHex, `${fixture.name}: canonical encode`);
	deepStrictEqual(decodeChange(encodeChange(decoded)), decoded, `${fixture.name}: every decoded payload roundtrips`);
	const serialized = JSON.stringify(decoded);
	equal(changeId(JSON.parse(serialized)), fixture.id, `${fixture.name}: JSON persistence`);
	equal(JSON.stringify(decoded), serialized, `${fixture.name}: does not mutate input`);
}

// Map names may overlap schema names. Key order matters and must not be sorted;
// JS integer-index keys retain their ordinary Object.keys enumeration semantics.
const entries = Object.fromEntries([
	["z", { bytesValue: "AAH/" }],
	["entries", { stringValue: "opaque map key" }],
	["__proto__", { boolValue: false }],
	["a", { mapValue: { entries: { z: { intValue: 1 }, a: { intValue: 2 } } } }],
]);
const change: ChangeJSON = {
	id: "", objectId: "maps", parentIds: [], timestamp: 1, author: "a",
	ops: [{ fieldSet: { key: "map", value: { mapValue: { entries } } } }],
};
const roundtrip = decodeChange(encodeChange(change));
ok(roundtrip);
deepStrictEqual(roundtrip.ops, change.ops);
const reverse: ChangeJSON = {
	...change,
	ops: [{ fieldSet: { key: "map", value: { mapValue: { entries: Object.fromEntries(Object.entries(entries).reverse()) } } } }],
};
notEqual(changeId(change), changeId(reverse), "map insertion order is part of the legacy content address");
deepStrictEqual(unpackCoreValueMaps(packCoreValueMaps(change)), change, "map transport preserves opaque keys");

for (const hex of [
	"00", "0a80", "22021a01", "22041a021201", "3a032a0100",
	"22091a0712051900000000", "22020a01", "3a023200",
	"2880808080808080808002", "0affffffffffffffffff01",
]) {
	equal(decodeChange(Uint8Array.from(Buffer.from(hex, "hex"))), null, `${hex}: malformed nested wire`);
}
for (const bytes of ["=", "===", "a", "AA=A", "!!!!"]) {
	throws(() => coreCall("codec", { action: "decode", bytes }), undefined, "invalid base64 rejected");
}
console.log(`Codec parity: ${fixtures.length} fixed native/WASM goldens; payload, map-order, and malformed-wire cases`);
